programacao/python/flask/game-library/flaskr/views/auth.py
from flask import Blueprint, flash, redirect, render_template, url_for
from werkzeug import Response

from flaskr.controllers.auth_controller import auth, origin, set_session_user
from flaskr.utils import is_post_request, UserForm
from flaskr.views.types import Renderable

bp = Blueprint("auth", __name__, url_prefix="/auth")


@bp.route("/login", methods=["GET", "POST"])
def login() -> Renderable:
    if is_post_request():
        return auth()
    return render_template(
        "login.html", a_title="Login", origin=origin(), form=UserForm()
    )


@bp.route("/logout")
def logout() -> Response:
    set_session_user(None)
    flash("Logout succesful!")
    return redirect(url_for("game_library.index"))

programacao/python/flask/game-library/flaskr/views/game_library.py
from flask import (
    Blueprint,
    flash,
    redirect,
    render_template,
    send_from_directory,
    url_for,
)
from werkzeug import Response

from flaskr.controllers.game_library_controller import (
    list_games,
    create_game,
    get_game_by_id,
    update_game,
    delete_game_from_database,
)
from flaskr.utils import (
    is_post_request,
    is_user_logged_in,
    GameCoverUploader,
    GameForm,
)
from flaskr.utils.decorators import login_required
from flaskr.views.types import Game, Renderable

bp = Blueprint("game_library", __name__)


@bp.route("/")
def index() -> str:
    games = list_games()
    return render_template(
        "game_library/index.html",
        a_title="Games",
        table_data=games,
        is_user_logged_in=is_user_logged_in(),
    )


@bp.route("/create", methods=["GET", "POST"])
@login_required
def create() -> Renderable:
    if is_post_request():
        return create_game()
    return render_template(
        "game_library/create.html", a_title="Create a game", form=GameForm()
    )


@bp.route("/update/<int:id>", methods=["GET", "POST"])
@login_required
def update(id: int) -> Renderable:
    game = get_game_by_id(id)
    assert isinstance(game, Game)
    return (
        update_game(game)
        if is_post_request()
        else render_game_update_template(game)
    )


def render_game_update_template(a_game: Game) -> str:
    form = create_game_form_from_game(a_game)
    game_cover = GameCoverUploader(
        a_game.id
    ).retrieve_uploaded_cover_filename()
    return render_template(
        "game_library/update.html",
        a_title="Updating a game",
        game_id=a_game.id,
        form=form,
        game_cover=game_cover,
    )


def create_game_form_from_game(a_game: Game) -> GameForm:
    result = GameForm()
    result.name.data = a_game.name
    result.genre.data = a_game.genre
    result.platform.data = a_game.platform
    return result


@bp.route("/delete/<int:id>")
@login_required
def delete(id: int) -> Response:
    game = get_game_by_id(id)
    delete_game_from_database(game)
    flash("Game deleted successfully!")
    return redirect(url_for("game_library.index"))


@bp.route("/uploads/<filename>")
def image(filename: str) -> Response:
    return send_from_directory("uploads", filename)

programacao/python/flask/game-library/flaskr/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Game Library</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='app.css') }}">
  </head>
  <body>
    <div class="container">

      {% with messages = get_flashed_messages() %}
        {% if messages %}
          <ul id="messages" class="list-unstyled">
            {% for message in messages %}
              <li class="alert alert-success">{{ message }}</li>
            {% endfor %}
          </ul>
        {% endif %}
      {% endwith %}

      <div class="page-header">
        <h1>{{ a_title }}</h1>
      </div>

      {% block content %} {% endblock %}

      <script type="text/javascript" src="{{ url_for('static', filename='jquery.js') }}"></script>
      <script type="text/javascript" src="{{ url_for('static', filename='app.js') }}"></script>
    </div>
  </body>
</html>

programacao/python/flask/game-library/flaskr/templates/form.html
{% extends "template.html" %}
{% block content %}
  <form action="{{url_for('game_library.create')}}" method="post">
    <fieldset>
      <div class="form-group">
        <label for="name">Name</label>
        <input type="text" name="name" id="name" class="form-control">
      </div>
      <div class="form-group">
        <label for="genre">Genre</label>
        <input type="text" name="genre" id="genre" class="form-control">
      </div>
      <div class="form-group">
        <label for="platform">Platform</label>
        <input type="text" name="platform" id="platform" class="form-control">
      </div>
      <button type="submit" class="btn btn-primary btn-save">Save</button>
    </fieldset>
  </form>
{% endblock %}

programacao/python/flask/game-library/flaskr/templates/index.html
{% extends "template.html" %}
{% block content %}
  <table class="table table-striped table-responsive table-bordered">
    <thead class="thead-default">
      <tr>
        <th>Name</th>
        <th>Genre</th>
        <th>Platform</th>
      </tr>
    </thead>
    <tbody>
      {% for data in table_data %}
      <tr>
        <td>{{ data.name }}</td>
        <td>{{ data.genre }}</td>
        <td>{{ data.platform }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

programacao/python/flask/game-library/flaskr/templates/login.html
{% extends "base.html" %}
{% block content %}
  <form action="{{url_for('auth.login')}}" method="post">
    <input type="hidden" name="origin" value="{{ origin }}">
    {{ form.csrf_token }}
    <div class="form-group input-box">
      {{ form.username.label(class="form-label") }}
      {{ form.username(class="form-control") }}
    </div>
    <div class="form-group input-box">
      {{ form.password.label(class="form-label") }}
      {{ form.password(class="form-control") }}
    </div>
    <div class="form-group buttons">
      {{ form.login(class="btn btn-primary") }}
      <a href="{{ url_for('game_library.index')}}" class="btn btn-danger">Back</a>
    </div>
    
  </form>
{% endblock %}

programacao/python/flask/game-library/flaskr/templates/template.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Game Library</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.css') }}">
  </head>
  <body>
    <div class="container">
      <div class="page-header">
        <h1>{{ a_title }}</h1>
      </div>
      {% block content %} {% endblock %}
      {% with messages = get_flashed_messages() %}
        {% if messages %}
          <ul id="messages" class="list-unstyled">
            {% for message in messages %}
              <li class="alert alert-success">{{ message }}</li>
            {% endfor %}
          </ul>
        {% endif %}
      {% endwith %}
    </div>
  </body>
</html>