programacao/python/flask/game-library/flaskr/game_library/models.py
from flaskr import db


class Game(db.Model):
    __tablename__ = "games"

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.String(50), nullable=False)
    genre = db.Column(db.String(40), nullable=False)
    platform = db.Column(db.String(20), nullable=False)

    def __repr__(self) -> str:
        return '<Name %r>' % self.name

programacao/python/flask/game-library/flaskr/auth.py
from typing import Optional, Union

from flask import (
    Blueprint,
    flash,
    redirect,
    render_template,
    request,
    session,
    url_for,
)
from werkzeug import Response

from flaskr import db
from flaskr.db_new import Users

bp = Blueprint("auth", __name__, url_prefix="/auth")


@bp.route("/login", methods=["GET", "POST"])
def login() -> Union[Response, str]:
    if request.method == "POST":
        return auth(request.form["username"])
    return render_template("login.html", a_title="Login", origin=origin())


def auth(a_username: str) -> Response:
    if user := is_there_a_user_with_username(a_username):
        if does_password_match(user.password):
            return succesful_user_login(user.username)
    flash("User not logged in.")
    return redirect(url_for("auth.login"))


def is_there_a_user_with_username(a_username: str) -> Optional[Users]:
    return db.session.execute(
        db.select(Users).filter_by(username=a_username)
    ).scalar()


def does_password_match(a_password: str) -> bool:
    return request.form["password"] == a_password


def succesful_user_login(a_username: str) -> Response:
    set_session_user(a_username)
    flash(f"{a_username} logged in succesfully!")
    return redirect(origin_of_request())


def set_session_user(a_username: Union[str, None]) -> None:
    session["logged_in_user"] = a_username


def origin_of_request() -> str:
    return request.form["origin"]


@bp.route("/logout")
def logout() -> Response:
    set_session_user(None)
    flash("Logout succesful!")
    return redirect(url_for("game_library.index"))


def origin() -> str:
    return request.args.get("origin") or ""

programacao/python/flask/game-library/flaskr/controllers/game_library_controller.py
from typing import Optional

from flask import flash, redirect, request, url_for
from werkzeug import Request, Response

from flaskr import db
from flaskr.models import Game
from flaskr.utils import GameForm, GameCoverUploader


def list_games() -> list[Game]:
    select_all_games = db.select(Game).order_by(Game.name)
    return list(db.session.execute(select_all_games).scalars())


def create_game() -> Response:
    form = GameForm(request.form)
    return (
        handle_game_creation(form)
        if form.validate_on_submit()
        else redirect(url_for("game_library.create"))
    )


def handle_game_creation(a_form: GameForm) -> Response:
    if is_game_with_name_in_database(a_form.name.data):
        flash("Game already exists!")
    else:
        create_game_from_data(a_form, request)
    return redirect(url_for("game_library.index"))


def is_game_with_name_in_database(a_name: str) -> bool:
    select_game_by_name = db.select(Game).filter_by(name=a_name)
    return bool(db.session.execute(select_game_by_name).scalar())


def create_game_from_data(a_form: GameForm, a_request: Request) -> None:
    game = Game(
        name=a_form.name.data,
        genre=a_form.genre.data,
        platform=a_form.platform.data,
    )
    cover_art = a_request.files["cover-art"]

    add_game_to_database(game)
    GameCoverUploader(game.id).upload_cover_file(cover_art)


def add_game_to_database(a_game: Game) -> None:
    db.session.add(a_game)
    db.session.commit()


def get_game_by_id(an_id: int) -> Optional[Game]:
    select_game_by_id = db.select(Game).filter_by(id=an_id)
    return db.session.execute(select_game_by_id).scalar()


def update_game(a_game: Game) -> Response:
    form = GameForm(request.form)
    if form.validate_on_submit():
        update_game_from_form(a_game, form)
        update_game_cover(a_game)
    return redirect(url_for("game_library.index"))


def update_game_from_form(a_game: Game, a_form: GameForm) -> None:
    a_game.name = a_form.name.data
    a_game.genre = a_form.genre.data
    a_game.platform = a_form.platform.data
    db.session.commit()


def update_game_cover(a_game: Game) -> None:
    game_cover = request.files["cover-art"]
    cover_file_manager = GameCoverUploader(a_game.id)
    cover_file_manager.update_cover_file(game_cover)


def delete_game_from_database(a_game: Optional[Game]) -> None:
    db.session.delete(a_game)
    db.session.commit()

programacao/python/flask/game-library/flaskr/game_library/views.py
from typing import Union

from flask import (
    Blueprint,
    flash,
    redirect,
    render_template,
    request,
    send_from_directory,
    url_for,
)
from werkzeug import Request, Response

from flaskr import db
from flaskr.auth.views import is_user_logged_in, login_required
from flaskr.game_library.models import Game
from flaskr.game_library.helpers import GameForm, GameCoverUploader

bp = Blueprint("game_library", __name__)


@bp.route("/")
def index() -> str:
    games = db.session.execute(db.select(Game).order_by(Game.name)).scalars()
    return render_template(
        "game_library/index.html",
        a_title="Games",
        table_data=games,
        is_user_logged_in=is_user_logged_in(),
    )


@bp.route("/create", methods=["GET", "POST"])
@login_required
def create() -> Union[Response, str]:
    if request.method == "POST":
        return create_game()
    form = GameForm()
    return render_template(
        "game_library/create.html", a_title="Create a game", form=form
    )


def create_game() -> Response:
    form = GameForm(request.form)
    if not form.validate_on_submit():
        return redirect(url_for("game_library.create"))
    if is_game_with_name_in_database(form.name.data):
        flash("Game already exists!")
    else:
        create_game_from_data(form, request)
    return redirect(url_for("game_library.index"))


def is_game_with_name_in_database(a_name: str) -> bool:
    return bool(
        db.session.execute(db.select(Game).filter_by(name=a_name)).scalar()
    )


def create_game_from_data(
    a_form: GameForm, a_request: Request
) -> None:
    game = Game(
        name=a_form.name.data,
        genre=a_form.genre.data,
        platform=a_form.platform.data,
    )
    cover_art = a_request.files["cover-art"]

    add_game_to_database(game)
    GameCoverUploader(game.id).upload_cover_file(cover_art)


def add_game_to_database(a_game: Game) -> None:
    db.session.add(a_game)
    db.session.commit()


@bp.route("/update/<int:id>", methods=["GET", "POST"])
@login_required
def update(id: int) -> Union[Response, str]:
    game = db.session.execute(db.select(Game).filter_by(id=id)).scalar()
    assert isinstance(game, Game)
    form = GameForm()
    form.name.data = game.name
    form.genre.data = game.genre
    form.platform.data = game.platform
    game_cover = GameCoverUploader(id).retrieve_uploaded_cover_filename()
    if request.method == "POST":
        return update_game(game)
    return render_template(
        "game_library/update.html",
        a_title="Updating a game",
        game_id=id,
        form=form,
        game_cover=game_cover,
    )


def update_game(a_game: Game) -> Response:
    form = GameForm(request.form)
    if form.validate_on_submit():
        a_game.name = form.name.data
        a_game.genre = form.genre.data
        a_game.platform = form.platform.data
        game_cover = request.files["cover-art"]
        db.session.commit()

        cover_file_manager = GameCoverUploader(a_game.id)
        cover_file_manager.delete_cover_file()
        cover_file_manager.upload_cover_file(game_cover)

    return redirect(url_for("game_library.index"))


@bp.route("/delete/<int:id>")
@login_required
def delete(id: int) -> Response:
    game = db.session.execute(db.select(Game).filter_by(id=id)).scalar()
    db.session.delete(game)
    db.session.commit()
    flash("Game deleted successfully!")
    return redirect(url_for("game_library.index"))


@bp.route("/uploads/<filename>")
def image(filename: str) -> Response:
    return send_from_directory("uploads", filename)

programacao/python/flask/game-library/flaskr/views/game_library.py
from flask import (
    Blueprint,
    flash,
    redirect,
    render_template,
    send_from_directory,
    url_for,
)
from werkzeug import Response

from flaskr.controllers.game_library_controller import (
    list_games,
    create_game,
    get_game_by_id,
    update_game,
    delete_game_from_database,
)
from flaskr.utils import (
    is_post_request,
    is_user_logged_in,
    GameCoverUploader,
    GameForm,
)
from flaskr.utils.decorators import login_required
from flaskr.views.types import Game, Renderable

bp = Blueprint("game_library", __name__)


@bp.route("/")
def index() -> str:
    games = list_games()
    return render_template(
        "game_library/index.html",
        a_title="Games",
        table_data=games,
        is_user_logged_in=is_user_logged_in(),
    )


@bp.route("/create", methods=["GET", "POST"])
@login_required
def create() -> Renderable:
    if is_post_request():
        return create_game()
    return render_template(
        "game_library/create.html", a_title="Create a game", form=GameForm()
    )


@bp.route("/update/<int:id>", methods=["GET", "POST"])
@login_required
def update(id: int) -> Renderable:
    game = get_game_by_id(id)
    assert isinstance(game, Game)
    return (
        update_game(game)
        if is_post_request()
        else render_game_update_template(game)
    )


def render_game_update_template(a_game: Game) -> str:
    form = create_game_form_from_game(a_game)
    game_cover = GameCoverUploader(
        a_game.id
    ).retrieve_uploaded_cover_filename()
    return render_template(
        "game_library/update.html",
        a_title="Updating a game",
        game_id=a_game.id,
        form=form,
        game_cover=game_cover,
    )


def create_game_form_from_game(a_game: Game) -> GameForm:
    result = GameForm()
    result.name.data = a_game.name
    result.genre.data = a_game.genre
    result.platform.data = a_game.platform
    return result


@bp.route("/delete/<int:id>")
@login_required
def delete(id: int) -> Response:
    game = get_game_by_id(id)
    delete_game_from_database(game)
    flash("Game deleted successfully!")
    return redirect(url_for("game_library.index"))


@bp.route("/uploads/<filename>")
def image(filename: str) -> Response:
    return send_from_directory("uploads", filename)

programacao/python/flask/game-library/flaskr/templates/game_library/create.html
{% extends "base.html" %}
{% block content %}
<form action="{{url_for('game_library.create')}}" method="post" enctype="multipart/form-data" class="game-form">
  <figure class="img-thumbnail col-md-4 form-image">
    <img src="{{ url_for('game_library.image', filename='default_cover.jpg') }}" alt="default cover" class="img-fluid">
    <label for="cover-art" class="file-container">
      Change cover
      <input type="file" accept=".jpg" name="cover-art" id="cover-art" class="form-control">
    </label>
  </figure>
  <fieldset>
    {{ form.csrf_token }}
    <div class="form-group input-box">
      {{ form.name.label(class="form-label") }}
      {{ form.name(class="form-control") }}
    </div>
    <div class="form-group input-box">
      {{ form.genre.label(class="form-label") }}
      {{ form.genre(class="form-control") }}
    </div>
    <div class="form-group input-box">
      {{ form.platform.label(class="form-label") }}
      {{ form.platform(class="form-control") }}
    </div>
    <div class="form-group buttons">
      {{ form.save(class="btn btn-primary") }}
      <a href="{{ url_for('game_library.index') }}" class="btn btn-danger">Back</a>
    </div>
  </fieldset>
</form>
{% endblock %}

programacao/python/flask/game-library/flaskr/templates/game_library/index.html
{% extends "base.html" %}
{% block content %}
  {% if is_user_logged_in %}
    <a href="{{ url_for('auth.logout')}}" class="btn btn-danger">Logout</a>
    <a href="{{ url_for('game_library.create')}}" class="btn btn-primary">New Game</a>
  {% else %}
    <a href="{{ url_for('auth.login')}}" class="btn btn-primary">Login</a>
  {% endif %}
  <table class="table table-striped table-responsive table-bordered">
    <thead class="thead-default">
      <tr>
        <th>Name</th>
        <th>Genre</th>
        <th>Platform</th>
      </tr>
    </thead>
    <tbody>
      {% for data in table_data %}
      <tr>
        <td>{{ data.name }}</td>
        <td>{{ data.genre }}</td>
        <td>{{ data.platform }}</td>
        <td><a href="{{ url_for('game_library.update', id=data.id) }}">Edit</a></td>
        <td><a href="{{ url_for('game_library.delete', id=data.id) }}">Delete</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

programacao/python/flask/game-library/flaskr/templates/game_library/update.html
{% extends "base.html" %}
{% block content %}
  <form action="{{ url_for('game_library.update', id=game_id)}}" method="post" enctype="multipart/form-data" class="game-form">
    <figure class="img-thumbnail col-md-4 form-image">
      <img src="{{ url_for('game_library.image', filename=game_cover) }}" alt="default cover" class="img-fluid">
      <label for="cover-art" class="file-container">
        Change cover
        <input type="file" accept=".jpg" name="cover-art" id="cover-art" class="form-control">
      </label>
    </figure>
    <fieldset>
      <input type="hidden" name="id" value="{{ game_id }}">
      {{ form.csrf_token }}
    <div class="form-group input-box">
      {{ form.name.label(class="form-label") }}
      {{ form.name(class="form-control") }}
    </div>
    <div class="form-group input-box">
      {{ form.genre.label(class="form-label") }}
      {{ form.genre(class="form-control") }}
    </div>
    <div class="form-group input-box">
      {{ form.platform.label(class="form-label") }}
      {{ form.platform(class="form-control") }}
    </div>
    <div class="form-group buttons">
      {{ form.save(class="btn btn-primary") }}
      <a href="{{ url_for('game_library.index') }}" class="btn btn-danger">Back</a>
    </div>
    </fieldset>
  </form>
{% endblock %}